import {
    Award,
    BadgeCheck,
    Bike,
    Bolt,
    Box,
    Cake,
    Camera,
    Check,
    CircleHelp,
    Clock,
    Cloud,
    Coffee,
    CreditCard,
    Facebook,
    Flower2,
    Gift,
    Globe,
    Hand,
    Heart,
    Instagram,
    Leaf,
    Lightbulb,
    Linkedin,
    Lock,
    Mail,
    MapPin,
    Medal,
    MessageCircle,
    Music,
    Package,
    Phone,
    Recycle,
    RefreshCw,
    Rocket,
    Send,
    ShieldCheck,
    ShoppingBag,
    Smile,
    Sparkles,
    Star,
    Sun,
    Tag,
    ThumbsUp,
    Timer,
    Truck,
    Twitter,
    Undo2,
    Users,
    Wallet,
    Youtube,
    Zap,
    type LucideIcon,
} from 'lucide-react';

/** Curated icon set for the page-builder `icon` field. Keyed by a stable slug. */
export const ICONS: Record<string, LucideIcon> = {
    star: Star,
    heart: Heart,
    check: Check,
    'badge-check': BadgeCheck,
    'shield-check': ShieldCheck,
    sparkles: Sparkles,
    leaf: Leaf,
    flower: Flower2,
    recycle: Recycle,
    sun: Sun,
    cloud: Cloud,
    zap: Zap,
    bolt: Bolt,
    rocket: Rocket,
    lightbulb: Lightbulb,
    award: Award,
    medal: Medal,
    gift: Gift,
    tag: Tag,
    'shopping-bag': ShoppingBag,
    package: Package,
    box: Box,
    truck: Truck,
    bike: Bike,
    'credit-card': CreditCard,
    wallet: Wallet,
    lock: Lock,
    clock: Clock,
    timer: Timer,
    'refresh-cw': RefreshCw,
    'undo-2': Undo2,
    'map-pin': MapPin,
    phone: Phone,
    mail: Mail,
    send: Send,
    'message-circle': MessageCircle,
    'circle-help': CircleHelp,
    users: Users,
    smile: Smile,
    'thumbs-up': ThumbsUp,
    hand: Hand,
    coffee: Coffee,
    cake: Cake,
    camera: Camera,
    music: Music,
    globe: Globe,
    facebook: Facebook,
    instagram: Instagram,
    twitter: Twitter,
    youtube: Youtube,
    linkedin: Linkedin,
};

export const ICON_NAMES = Object.keys(ICONS);

export function IconGlyph({
    name,
    className,
    style,
}: {
    name: string;
    className?: string;
    style?: React.CSSProperties;
}) {
    const Cmp = ICONS[name] ?? Star;
    return <Cmp className={className} style={style} />;
}

/** Social networks for the Social Icons widget, in a fixed order. */
export const SOCIAL_NETWORKS: { value: string; label: string }[] = [
    { value: 'facebook', label: 'Facebook' },
    { value: 'instagram', label: 'Instagram' },
    { value: 'twitter', label: 'X / Twitter' },
    { value: 'youtube', label: 'YouTube' },
    { value: 'linkedin', label: 'LinkedIn' },
    { value: 'globe', label: 'Website' },
    { value: 'mail', label: 'Email' },
    { value: 'phone', label: 'Phone' },
];
